name: CI Build & Tests

on:
  push:
    branches:
      - 'feature/**'   # Toutes les branches qui commencent par feature/
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Test & SonarQube (PR only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK (Corretto 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run unit tests
        run: ./gradlew test

      - name: SonarQube Scan
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.gradle.skipCompile=true
